"""Generic auracle product backend — auto-generated by compose_product.

Do not hand-edit unless you're willing to take ownership — the next
compose run will overwrite this file.

AURACLE_EMIT_VERSION:iter23 — see compose.py _is_stale_compose for the
short-circuit-bypass marker. Bump when emit_server's contract changes
in a way that requires already-composed product repos to be re-emitted.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import time
from pathlib import Path
from typing import Any

from aiohttp import web

# adapters.py is copied alongside this file at compose time.
try:
    from . import adapters
except ImportError:
    from server import adapters  # type: ignore[no-redef]

log = logging.getLogger("auracle_product")

STATIC_DIR = Path(__file__).resolve().parent.parent
PORT = int(os.environ.get("PORT", "8080"))

ROUTES: list[dict] = [
  {
    "path": "/mock-data.js",
    "method": "GET",
    "kind": "window-mock",
    "leaves": {
      "KPIS.p0_incidents_24h.delta": {
        "adapter": "static_value",
        "args": {
          "value": ""
        }
      },
      "KPIS.p0_incidents_24h.spark": {
        "adapter": "bq_topic_sparkline",
        "args": {
          "topic": "factory.incident",
          "hours": 24
        }
      },
      "KPIS.p0_incidents_24h.val": {
        "adapter": "bq_count_by_topic",
        "args": {
          "topic": "factory.incident",
          "hours": 24
        },
        "postprocess": "to_int"
      },
      "KPIS.deploys_24h.delta": {
        "adapter": "static_value",
        "args": {
          "value": ""
        }
      },
      "KPIS.deploys_24h.spark": {
        "adapter": "bq_topic_sparkline",
        "args": {
          "topic": "factory.deploy",
          "hours": 24
        }
      },
      "KPIS.intents_24h.delta": {
        "adapter": "static_value",
        "args": {
          "value": ""
        }
      },
      "KPIS.intents_24h.spark": {
        "adapter": "bq_topic_sparkline",
        "args": {
          "topic": "factory.tasks",
          "hours": 24
        }
      },
      "KPIS.services_up.delta": {
        "adapter": "static_value",
        "args": {
          "value": ""
        }
      },
      "KPIS.services_up.spark": {
        "adapter": "bq_topic_sparkline",
        "args": {
          "topic": "factory.tasks",
          "hours": 24
        }
      },
      "KPIS.services_up.total": {
        "adapter": "cloudrun_services_count",
        "args": {},
        "postprocess": "to_int"
      },
      "KPIS.deploys_24h.val": {
        "adapter": "bq_count_by_topic",
        "args": {
          "topic": "factory.deploy",
          "hours": 24
        },
        "postprocess": "to_int"
      },
      "KPIS.intents_24h.val": {
        "adapter": "bq_count_by_topic",
        "args": {
          "topic": "factory.tasks",
          "hours": 24
        },
        "postprocess": "to_int"
      },
      "KPIS.services_up.val": {
        "adapter": "cloudrun_services_count",
        "args": {},
        "postprocess": "to_int"
      },
      "MEMORY_ENTRIES[]": {
        "adapter": "static_value",
        "args": {
          "value": None
        }
      },
      "NEW_SKILLS[].id": {
        "adapter": "static_value",
        "args": {
          "value": None
        }
      },
      "SEARCH_ITEMS": {
        "adapter": "static_value",
        "args": {
          "value": None
        }
      },
      "THREADS[].id": {
        "adapter": "static_value",
        "args": {
          "value": None
        }
      },
      "AGENTS[].id": {
        "adapter": "static_value",
        "args": {
          "value": None
        }
      },
      "INFLIGHT": {
        "adapter": "static_value",
        "args": {
          "value": None
        }
      },
      "PROJECTS": {
        "adapter": "static_value",
        "args": {
          "value": None
        }
      },
      "TOPICS[]": {
        "adapter": "static_value",
        "args": {
          "value": None
        }
      },
      "fmtTime": {
        "adapter": "static_value",
        "args": {
          "value": None
        }
      },
      "EVENTS": {
        "adapter": "static_value",
        "args": {
          "value": None
        }
      },
      "MEMORY": {
        "adapter": "static_value",
        "args": {
          "value": None
        }
      },
      "RETROS": {
        "adapter": "static_value",
        "args": {
          "value": None
        }
      },
      "SKILLS": {
        "adapter": "static_value",
        "args": {
          "value": None
        }
      },
      "fmtRel": {
        "adapter": "static_value",
        "args": {
          "value": None
        }
      },
      "CHAT": {
        "adapter": "static_value",
        "args": {
          "value": None
        }
      },
      "NOW": {
        "adapter": "static_value",
        "args": {
          "value": None
        }
      }
    },
    "helpers": {
      "fmtRel": "const fmtRel = (ts) => {\n    const d = NOW - ts;\n    if (d < 60 * SEC) return Math.max(1, Math.round(d / SEC)) + 's ago';\n    if (d < 60 * MIN) return Math.round(d / MIN) + 'm ago';\n    if (d < 24 * HR)  return Math.round(d / HR) + 'h ago';\n    return Math.round(d / DAY) + 'd ago';\n  }",
      "makeEvent": "const makeEvent = (i) => {\n    const t = EVT_TEMPLATES[i % EVT_TEMPLATES.length];\n    return {\n      id: 'evt_' + (NOW - i * 1234).toString(36),\n      ts: NOW - i * (12 + (i * 7) % 40) * SEC,\n      topic: t.topic,\n      skill: t.skill,\n      stepId: 'stp_' + (0xb000 + i * 41).toString(16),\n      status: t.status,\n    };\n  }",
      "fmtTime": "const fmtTime = (ts) => {\n    const d = new Date(ts);\n    const hh = String(d.getHours()).padStart(2, '0');\n    const mm = String(d.getMinutes()).padStart(2, '0');\n    const ss = String(d.getSeconds()).padStart(2, '0');\n    return hh + ':' + mm + ':' + ss;\n  }"
    }
  }
]

_MOCK_SHAPE: dict = {}

MOCK_BINDINGS: dict = {
  "path": "/mock-data.js",
  "method": "GET",
  "kind": "window-mock",
  "leaves": {
    "KPIS.p0_incidents_24h.delta": {
      "adapter": "static_value",
      "args": {
        "value": ""
      }
    },
    "KPIS.p0_incidents_24h.spark": {
      "adapter": "bq_topic_sparkline",
      "args": {
        "topic": "factory.incident",
        "hours": 24
      }
    },
    "KPIS.p0_incidents_24h.val": {
      "adapter": "bq_count_by_topic",
      "args": {
        "topic": "factory.incident",
        "hours": 24
      },
      "postprocess": "to_int"
    },
    "KPIS.deploys_24h.delta": {
      "adapter": "static_value",
      "args": {
        "value": ""
      }
    },
    "KPIS.deploys_24h.spark": {
      "adapter": "bq_topic_sparkline",
      "args": {
        "topic": "factory.deploy",
        "hours": 24
      }
    },
    "KPIS.intents_24h.delta": {
      "adapter": "static_value",
      "args": {
        "value": ""
      }
    },
    "KPIS.intents_24h.spark": {
      "adapter": "bq_topic_sparkline",
      "args": {
        "topic": "factory.tasks",
        "hours": 24
      }
    },
    "KPIS.services_up.delta": {
      "adapter": "static_value",
      "args": {
        "value": ""
      }
    },
    "KPIS.services_up.spark": {
      "adapter": "bq_topic_sparkline",
      "args": {
        "topic": "factory.tasks",
        "hours": 24
      }
    },
    "KPIS.services_up.total": {
      "adapter": "cloudrun_services_count",
      "args": {},
      "postprocess": "to_int"
    },
    "KPIS.deploys_24h.val": {
      "adapter": "bq_count_by_topic",
      "args": {
        "topic": "factory.deploy",
        "hours": 24
      },
      "postprocess": "to_int"
    },
    "KPIS.intents_24h.val": {
      "adapter": "bq_count_by_topic",
      "args": {
        "topic": "factory.tasks",
        "hours": 24
      },
      "postprocess": "to_int"
    },
    "KPIS.services_up.val": {
      "adapter": "cloudrun_services_count",
      "args": {},
      "postprocess": "to_int"
    },
    "MEMORY_ENTRIES[]": {
      "adapter": "static_value",
      "args": {
        "value": None
      }
    },
    "NEW_SKILLS[].id": {
      "adapter": "static_value",
      "args": {
        "value": None
      }
    },
    "SEARCH_ITEMS": {
      "adapter": "static_value",
      "args": {
        "value": None
      }
    },
    "THREADS[].id": {
      "adapter": "static_value",
      "args": {
        "value": None
      }
    },
    "AGENTS[].id": {
      "adapter": "static_value",
      "args": {
        "value": None
      }
    },
    "INFLIGHT": {
      "adapter": "static_value",
      "args": {
        "value": None
      }
    },
    "PROJECTS": {
      "adapter": "static_value",
      "args": {
        "value": None
      }
    },
    "TOPICS[]": {
      "adapter": "static_value",
      "args": {
        "value": None
      }
    },
    "fmtTime": {
      "adapter": "static_value",
      "args": {
        "value": None
      }
    },
    "EVENTS": {
      "adapter": "static_value",
      "args": {
        "value": None
      }
    },
    "MEMORY": {
      "adapter": "static_value",
      "args": {
        "value": None
      }
    },
    "RETROS": {
      "adapter": "static_value",
      "args": {
        "value": None
      }
    },
    "SKILLS": {
      "adapter": "static_value",
      "args": {
        "value": None
      }
    },
    "fmtRel": {
      "adapter": "static_value",
      "args": {
        "value": None
      }
    },
    "CHAT": {
      "adapter": "static_value",
      "args": {
        "value": None
      }
    },
    "NOW": {
      "adapter": "static_value",
      "args": {
        "value": None
      }
    }
  },
  "helpers": {
    "fmtRel": "const fmtRel = (ts) => {\n    const d = NOW - ts;\n    if (d < 60 * SEC) return Math.max(1, Math.round(d / SEC)) + 's ago';\n    if (d < 60 * MIN) return Math.round(d / MIN) + 'm ago';\n    if (d < 24 * HR)  return Math.round(d / HR) + 'h ago';\n    return Math.round(d / DAY) + 'd ago';\n  }",
    "makeEvent": "const makeEvent = (i) => {\n    const t = EVT_TEMPLATES[i % EVT_TEMPLATES.length];\n    return {\n      id: 'evt_' + (NOW - i * 1234).toString(36),\n      ts: NOW - i * (12 + (i * 7) % 40) * SEC,\n      topic: t.topic,\n      skill: t.skill,\n      stepId: 'stp_' + (0xb000 + i * 41).toString(16),\n      status: t.status,\n    };\n  }",
    "fmtTime": "const fmtTime = (ts) => {\n    const d = new Date(ts);\n    const hh = String(d.getHours()).padStart(2, '0');\n    const mm = String(d.getMinutes()).padStart(2, '0');\n    const ss = String(d.getSeconds()).padStart(2, '0');\n    return hh + ':' + mm + ':' + ss;\n  }"
  }
}

_cache: dict = {}
_CACHE_TTL = 30.0


async def _cached(key: str, fn: Any, *args: Any, **kwargs: Any) -> Any:
    now = time.monotonic()
    hit = _cache.get(key)
    if hit and (now - hit[0]) < _CACHE_TTL:
        return hit[1]
    val = await fn(*args, **kwargs)
    _cache[key] = (now, val)
    return val


async def _dispatch(binding: dict) -> Any:
    fn = getattr(adapters, binding["adapter"])
    return await fn(**binding.get("args", {}))


def _post(value: Any, kind: str | None) -> Any:
    if isinstance(value, Exception):
        return None
    if kind == "to_int":
        try:
            return int(value)
        except (TypeError, ValueError):
            if isinstance(value, list):
                return len(value)
            return 0
    if kind == "to_str":
        try:
            return str(value)
        except Exception:
            return ""
    if kind == "to_list":
        return list(value) if isinstance(value, (list, tuple)) else []
    return value


def _set_leaf(target: dict, path: str, value: Any) -> None:
    """Set target[a][b][c] = value where path == 'a.b.c'. Strips trailing [] from keys."""
    parts = path.split(".")
    cur = target
    for p in parts[:-1]:
        key = p[:-2] if p.endswith("[]") else p
        cur = cur.setdefault(key, {})
    last = parts[-1]
    key = last[:-2] if last.endswith("[]") else last
    cur[key] = value


def _make_handler(binding: dict) -> Any:
    async def _handler(request: web.Request) -> web.Response:
        try:
            data = await _cached(
                f"{binding['path']}:{binding['method']}",
                _dispatch,
                binding,
            )
            return web.json_response(data)
        except Exception as exc:
            log.exception("handler error path=%s: %s", binding["path"], exc)
            return web.json_response({"error": str(exc)}, status=500)
    return _handler


def _make_leaves_handler(binding: dict) -> Any:
    async def _handler(request: web.Request) -> web.Response:
        leaves = binding.get("leaves") or {}
        leaf_keys = list(leaves.keys())
        tasks = []
        for lk in leaf_keys:
            leaf = leaves[lk]
            fn = getattr(adapters, leaf["adapter"])
            tasks.append(fn(**leaf.get("args", {})))
        raw = await asyncio.gather(*tasks, return_exceptions=True)
        out: dict = {}
        for lk, result in zip(leaf_keys, raw):
            leaf = leaves[lk]
            _set_leaf(out, lk, _post(result, leaf.get("postprocess")))
        return web.json_response(out)
    return _handler


_MIME = {
    ".jsx": "application/javascript",
    ".js": "application/javascript",
    ".css": "text/css",
    ".html": "text/html",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".ico": "image/x-icon",
}


async def _build_mock_js() -> web.Response:
    """Build window.MOCK JS dynamically by overlaying live adapter results
    on top of the original mock-data.js fixtures.

    The original mock-data.js (copied verbatim from the templates into
    STATIC_DIR at compose time) defines window.MOCK with rich fixtures
    for every consumer key — AGENTS, EVENTS, THREADS, SKILLS, etc.
    Adapter bindings only cover a subset of leaves (typically the live
    KPIs). Serving the original file first preserves the demo UI for
    unbound keys; the patcher IIFE that follows overrides each bound
    leaf with the live adapter value at request time.

    Falls back to the previous bare-data mode when the original file is
    absent (test-templates / synthetic frontends that have no
    pre-existing mock-data.js).
    """
    leaves = MOCK_BINDINGS.get("leaves") or {}
    leaf_keys = list(leaves.keys())
    tasks = []
    for lk in leaf_keys:
        leaf = leaves[lk]
        fn = getattr(adapters, leaf["adapter"])
        tasks.append(fn(**leaf.get("args", {})))
    raw = await asyncio.gather(*tasks, return_exceptions=True)
    data: dict = {}
    flat: dict = {}
    for lk, result in zip(leaf_keys, raw):
        leaf = leaves[lk]
        val = _post(result, leaf.get("postprocess"))
        _set_leaf(data, lk, val)
        flat[lk] = val

    original_path = STATIC_DIR / "mock-data.js"
    if original_path.is_file():
        # Overlay mode: serve original fixtures, then patch bound leaves
        try:
            original_js = original_path.read_text(encoding="utf-8")
        except OSError:
            original_js = ""
        # iter-23: emit the patch as a FLAT dotted-path map (not the
        # nested data dict). The JS _set splits each path on '.' and
        # walks/creates the tree, so flat keys preserve sibling values
        # in the original fixtures (e.g. patching KPIS.services_up.val
        # leaves KPIS.intents_24h alone). Prune null/empty results so
        # the overlay doesn't clobber rich fixtures for unbound leaves.
        meaningful: dict = {}
        for path, val in flat.items():
            if val is None:
                continue
            if isinstance(val, (dict, list)) and not val:
                continue
            # Treat the `id: None` not-found shape from a lookup leaf
            # as empty too — the binding planner emits this when an
            # adapter call returns no row.
            if isinstance(val, dict) and len(val) == 1 and val.get("id") is None:
                continue
            meaningful[path] = val
        patcher_lines = [
            "(function () {",
            "  var _patch = " + json.dumps(meaningful) + ";",
            "  function _set(obj, path, val) {",
            "    var parts = path.split('.');",
            "    var cur = obj;",
            "    for (var i = 0; i < parts.length - 1; i++) {",
            "      var k = parts[i];",
            "      if (cur[k] === undefined || cur[k] === null) cur[k] = {};",
            "      cur = cur[k];",
            "    }",
            "    cur[parts[parts.length - 1]] = val;",
            "  }",
            "  if (typeof window !== 'undefined' && window.MOCK) {",
            "    Object.keys(_patch).forEach(function(path) {",
            "      _set(window.MOCK, path, _patch[path]);",
            "    });",
            "  }",
            "})();",
        ]
        patcher = chr(10).join(patcher_lines)
        body = (
            original_js
            + chr(10)
            + "/* ─── auracle live-data overlay (adapter-bound leaves) ─── */"
            + chr(10)
            + patcher
        )
        return web.Response(text=body, content_type="application/javascript")

    # Fallback: original mock-data.js missing — emit just the bound data
    helpers = MOCK_BINDINGS.get("helpers") or {}
    data_json = json.dumps(data)
    helper_items = list(helpers.items())
    helper_block = chr(10).join(src for _, src in helper_items)
    helper_names = ", ".join(name for name, _ in helper_items)
    lines = ["(function () {"]
    if helper_block:
        lines.append("  // ── helpers (verbatim from compose-time extraction) ─────────")
        lines.append(helper_block)
    lines.append("  // ── data (assembled at request time) ──────────────────")
    lines.append("  const _DATA = " + data_json + ";")
    if helper_names:
        lines.append("  window.MOCK = Object.assign({}, _DATA, { " + helper_names + " });")
    else:
        lines.append("  window.MOCK = _DATA;")
    lines.append("})();")
    return web.Response(text=chr(10).join(lines), content_type="application/javascript")


async def _mock_data_js(_: web.Request) -> web.Response:
    return await _cached("mock-data-js", _build_mock_js)


async def static_h(request: web.Request) -> web.Response:
    rel = request.match_info.get("path", "").lstrip("/")
    if not rel:
        rel = "index.html"
    target = (STATIC_DIR / rel).resolve()
    try:
        target.relative_to(STATIC_DIR)
    except ValueError:
        return web.Response(status=404)
    if not target.exists() or not target.is_file():
        target = STATIC_DIR / "index.html"
    return web.FileResponse(target, headers={
        "Content-Type": _MIME.get(target.suffix.lower(), "application/octet-stream")
    })


async def health(_: web.Request) -> web.Response:
    return web.Response(text="ok")


async def journeys_h(_: web.Request) -> web.Response:
    journeys_path = Path(__file__).resolve().parents[2] / "journeys.json"
    if journeys_path.exists():
        try:
            return web.json_response(json.loads(journeys_path.read_text(encoding="utf-8")))
        except Exception:
            pass
    return web.json_response([])


async def _self_ping() -> None:
    import aiohttp as _ah
    url = f"http://127.0.0.1:{PORT}/health"
    async with _ah.ClientSession() as sess:
        while True:
            try:
                async with sess.get(url, timeout=_ah.ClientTimeout(total=5)) as r:
                    await r.text()
            except Exception:
                pass
            await asyncio.sleep(30.0)


def build_app() -> web.Application:
    app = web.Application()
    app.router.add_get("/health", health)
    app.router.add_get("/journeys.json", journeys_h)
    # no API routes
    app.router.add_get("/mock-data.js", _mock_data_js)
    app.router.add_get("/", static_h)
    app.router.add_get("/{path:.*}", static_h)

    async def _on_startup(_app: web.Application) -> None:
        asyncio.create_task(_self_ping())

    app.on_startup.append(_on_startup)
    return app


def main() -> None:
    logging.basicConfig(level=logging.INFO)
    web.run_app(build_app(), host="0.0.0.0", port=PORT, print=None)


if __name__ == "__main__":
    main()
